
settings:
  ftp_user: "arista:arista"
  images_url: "ftp://192.168.59.5/"
  reports_url: "ftp://192.168.59.5/upload/"
  script_url: http://192.168.59.5/reimage.py
  startup_config_url: http://192.168.59.5/startup-config
  syslog_host: "192.168.59.5"

dhcp:
  lease_time: 3600
  bootfile: http://192.168.59.5/startup-config
  network: 192.168.59.0
  netmask: 255.255.255.0
  routers: 192.168.59.1
  range: [192.168.59.100, 192.168.59.254]

images:
  - pattern: vEOS
    image: vEOS-lab-4.21.2.3F.swi
    version: 4.21.2.3F

  - pattern: 7050QX-32S
    image: "EOS-4.21.2.3F.swi"
    version: "4.21.2.3F"

  - pattern:  7\d60CX
    image: "EOS-4.20.3F.swi"
    version: "4.20.3F"

  - pattern: 7170-64C
    image: "EOS-4.21.6.1.1F.swi"
    version: "4.21.6.1.1F"

  - pattern: 7280
    image: EOS-4.21.2.3F.swi
    version: 4.21.2.3F

  - pattern: 75\d{2}.?
    image: "EOS-4.21.2.3F.swi"
    version: "4.21.2.3F"